In [1]:
import tensorflow
import librosa
import librosa.display
import numpy as np
import matplotlib.pyplot as plt
import os
import pandas as pd

from sklearn.preprocessing import LabelEncoder

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

#Keras
import keras

import warnings
warnings.filterwarnings('ignore')

Using TensorFlow backend.


In [3]:
header = 'filename chroma_stft rmse spectral_centroid spectral_bandwidth rolloff zero_crossing_rate'
for i in range(1, 21):
    header += f' mfcc{i}'
header += ' label'
header = header.split()

In [ ]:
import pathlib
import csv
file = open('data.csv', 'w', newline='')
with file:
    writer = csv.writer(file)
    writer.writerow(header)
genres = 'blues classical country disco hiphop jazz metal pop reggae rock'.split()
for genre in genres:
    pathlib.Path(f'Resources/{genre}').mkdir(parents=True, exist_ok=True)
    for filename in os.listdir(f'GenreCollection/genres/{genre}'):
        songname = f'GenreCollection/genres/{genre}/{filename}'
        y, sr = librosa.load(songname, mono=True, duration=30)
        chroma_stft = librosa.feature.chroma_stft(y=y, sr=sr)
        spec_cent = librosa.feature.spectral_centroid(y=y, sr=sr)
        spec_bw = librosa.feature.spectral_bandwidth(y=y, sr=sr)
        rolloff = librosa.feature.spectral_rolloff(y=y, sr=sr)
        zcr = librosa.feature.zero_crossing_rate(y)
        mfcc = librosa.feature.mfcc(y=y, sr=sr)
        rmse = librosa.feature.rms(y=y)
        to_append = f'{filename} {np.mean(chroma_stft)} {np.mean(rmse)} {np.mean(spec_cent)} {np.mean(spec_bw)} {np.mean(rolloff)} {np.mean(zcr)}'    
        for e in mfcc:
            to_append += f' {np.mean(e)}'
        to_append += f' {genre}'
        file = open('data.csv', 'a', newline='')
        with file:
            writer = csv.writer(file)
            writer.writerow(to_append.split())

In [19]:
#reading in the data
data = pd.read_csv('data.csv')
data

filename  chroma_stft      rmse  spectral_centroid  \
0    blues.00000.au     0.349943  0.130225        1784.420446   
1    blues.00001.au     0.340983  0.095918        1529.835316   
2    blues.00002.au     0.363603  0.175573        1552.481958   
3    blues.00003.au     0.404779  0.141191        1070.119953   
4    blues.00004.au     0.308590  0.091563        1835.494603   
..              ...          ...       ...                ...   
995   rock.00095.au     0.351991  0.079469        2008.581132   
996   rock.00096.au     0.398653  0.076452        2006.051164   
997   rock.00097.au     0.432103  0.081617        2077.190361   
998   rock.00098.au     0.362349  0.083888        1398.672358   
999   rock.00099.au     0.358195  0.054461        1609.442919   

     spectral_bandwidth      rolloff  zero_crossing_rate       mfcc1  \
0           2002.650192  3806.485316            0.083066 -113.596748   
1           2038.617579  3548.820207            0.056044 -207.556793   
2           1747.165985  3040.514948            0.076301  -90.754387   
3           1596.333948  2185.028454            0.033309 -199.431152   
4           1748.362448  3580.945013            0.101500 -160.266037   
..                  ...          ...                 ...         ...   
995         2106.617024  4254.215942            0.089267 -153.632309   
996         2068.327905  4147.374921            0.097659 -142.424210   
997         1926.989678  4030.767293            0.121824 -125.031326   
998         1818.148469  3014.740104            0.048731 -224.972305   
999         1797.065098  3246.280370            0.076290 -235.189331   

          mfcc2      mfcc3  ...     mfcc12     mfcc13    mfcc14     mfcc15  \
0    121.557297 -19.158825  ...   8.810669  -3.667368  5.751691  -5.162763   
1    124.006721   8.930560  ...   5.376803  -2.239120  4.216963  -6.012273   
2    140.459900 -29.109968  ...   5.789265  -8.905224 -1.083720  -9.218359   
3    150.099213   5.647593  ...   6.087677  -2.476421 -1.073890  -2.874778   
4    126.198807 -35.605450  ...  -2.806384  -6.934123 -7.558618  -9.173553   
..          ...        ...  ...        ...        ...       ...        ...   
995  109.857262 -23.085709  ...  12.350818 -12.306271  5.780973 -10.279924   
996  116.219780 -32.177074  ...  14.065345 -16.394691  4.152589  -4.350760   
997  115.194977 -47.993507  ...  10.481961 -17.951916  1.211113 -11.534864   
998  123.656891  -9.754534  ...   7.683082 -10.071787 -0.255098  -5.276486   
999  123.888542 -22.536184  ...  10.066769 -15.019588  3.110468  -7.127754   

       mfcc16     mfcc17    mfcc18     mfcc19     mfcc20  label  
0    0.750948  -1.691938 -0.409953  -2.300209   1.219929  blues  
1    0.936109  -0.716537  0.293876  -0.287431   0.531573  blues  
2    2.455806  -7.726901 -1.815723  -3.433434  -2.226821  blues  
3    0.780977  -3.316932  0.637982  -0.619690  -3.408233  blues  
4   -4.512165  -5.453538 -0.924161  -4.409333 -11.703781  blues  
..        ...        ...       ...        ...        ...    ...  
995  1.791489 -13.304210  2.473193  -6.717574  -1.189238   rock  
996  3.736455 -10.845638  1.875218  -7.459579  -2.802677   rock  
997  1.844774 -12.847901  3.447425 -12.594178  -2.107002   rock  
998 -2.816288  -4.416438  1.558265  -5.043121  -3.585596   rock  
999  1.784515  -7.070405  0.023643  -2.022034   1.158525   rock  

[1000 rows x 28 columns]

In [5]:
# Dropping unneccesary columns
data = data.drop(['filename'],axis=1)

In [18]:
genre_list = data.iloc[:, -1]
encoder = LabelEncoder()
y = encoder.fit_transform(genre_list)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3,

In [7]:
scaler = StandardScaler()
X = scaler.fit_transform(np.array(data.iloc[:, :-1], dtype = float))

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [9]:
len(y_train)

800

In [10]:
len(y_test)

200

In [11]:
X_train[10]

array([ 0.56334647,  1.62005348,  0.17563805,  0.72980769,  0.22887359,
       -0.16597032,  0.33088291, -0.3063582 ,  0.61700039, -1.30627406,
        0.90696518, -2.03555274,  0.80656564, -0.98203808,  0.47322849,
       -0.56284989,  0.66508239, -0.43111247,  1.16798651, -0.58660594,
        0.97605289, -0.10144476, -0.26075072,  0.57551322,  1.24470643,
        0.22003211])

In [12]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

model = Sequential()
model.add(Dense(units=100, activation='relu', input_dim=26))
model.add(Dense(units=100, activation='relu'))
model.add(Dense(units=10, activation='softmax'))

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 100)               2700      
_________________________________________________________________
dense_1 (Dense)              (None, 100)               10100     
_________________________________________________________________
dense_2 (Dense)              (None, 10)                1010      
Total params: 13,810
Trainable params: 13,810
Non-trainable params: 0
_________________________________________________________________


In [13]:
model.compile(optimizer='adam', 
              loss='categorical_crossentropy', 
              metrics=['accuracy'])
model.fit(
    X_train,
    y_train,
    epochs=60,
    shuffle=True,
    verbose=2
)

Train on 800 samples
Epoch 1/60
800/800 - 1s - loss: 2.0714 - accuracy: 0.2925
Epoch 2/60
800/800 - 0s - loss: 1.6458 - accuracy: 0.3900
Epoch 3/60
800/800 - 0s - loss: 1.4300 - accuracy: 0.4737
Epoch 4/60
800/800 - 0s - loss: 1.2840 - accuracy: 0.5487
Epoch 5/60
800/800 - 0s - loss: 1.1754 - accuracy: 0.5987
Epoch 6/60
800/800 - 0s - loss: 1.0828 - accuracy: 0.6187
Epoch 7/60
800/800 - 0s - loss: 1.0156 - accuracy: 0.6600
Epoch 8/60
800/800 - 0s - loss: 0.9464 - accuracy: 0.6975
Epoch 9/60
800/800 - 0s - loss: 0.9046 - accuracy: 0.7025
Epoch 10/60
800/800 - 0s - loss: 0.8510 - accuracy: 0.7262
Epoch 11/60
800/800 - 0s - loss: 0.7972 - accuracy: 0.7450
Epoch 12/60
800/800 - 0s - loss: 0.7618 - accuracy: 0.7538
Epoch 13/60
800/800 - 0s - loss: 0.7149 - accuracy: 0.7738
Epoch 14/60
800/800 - 0s - loss: 0.6754 - accuracy: 0.7937
Epoch 15/60
800/800 - 0s - loss: 0.6441 - accuracy: 0.7987
Epoch 16/60
800/800 - 0s - loss: 0.6170 - accuracy: 0.8150
Epoch 17/60
800/800 - 0s - loss: 0.5810 - ac

In [14]:
# Save the model
model.save("genre_model_trained.h5")

In [17]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3,